
name: shibli_shorts
description: A demo Flutter shorts web app with upload + feed tabs.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.4.6
  video_player: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
